// backend/seeds/01_fields.js
// Canonical source for ALL field_registry definitions.
//
// HOW TO ADD A FIELD:
//   1. Add a row to the fields array below.
//   2. Run `npm run db:seed` (or restart via start.bat).
//   3. The field appears in the frontend via GET /api/fields/form/:record_type
//
// SHARED FIELDS: field_key is UNIQUE in field_registry. Fields used across
// multiple record types appear ONCE with a combined applicable_record_types array.
// Example: `io_name` has applicable_record_types: ['CASE','ARREST','PCR_CALL','MISSING','UIDB']
//
// This file uses ON CONFLICT (field_key) DO UPDATE so it is safe to re-run.

const L = JSON.stringify(['PS', 'DISTRICT', 'HQ']);
const E = JSON.stringify(['PS']);

const CRIME_HEADS = [
  'Simple Hurt','Other IPC','Other SLL','Kidnapping','Pick Pocketing','Gambling Act',
  'Cruelty by Husband','Simple Accident','Narcotics Drugs & Psychotropic Substances Act',
  'Robbery','Snatching','Murder','Delhi Excise Act','Att. to Murder','Burglary','Arms Act',
  'Other Theft','House Theft','Night Burglary','Rape','Copyright Act','Cheating',
  'Fatal Accident','Child Labour Act 1986',
  'Att. to Culpable Homicide not Amounting to Murder','Dowry Prohibition Act 1961',
  'Electricity Theft','Information Technology Act 2000','Grievous Hurt','Electricity Act 2003',
  'Other Act','Eve Teasing','Trade & Merchandise Marks Act, 1958','Mobile Phone Theft',
  'M.O. Women','Theft In Shop','POCSO Act 2012','Wild Life (Protection) Act 1972','Mischief',
  'Day Burglary','Encroachment on Govt. Land','Servant Theft','Ext. For Ransom','Extortion',
  'Counterfeiting','Criminal Breach of Trust','Criminal Intimidation','Threatening',
  'Environment (Protection) Act 1986','Affray','Arson','Abetment of Suicide',
  'Juvenile Justice Act 2015','Adultery',
  'The Delhi Prevention of Touting and Malpractices Against Tourists Ordinance Act 2010',
  'Att. to Commit Suicide','Acid Attack','Explosive Act 1884','Acid Attack Attempt',
  'Immoral Traffic(Prev.) Act, 1956 (SIT Act (Immoral))','Trespass','Delhi Police Act 1978',
  'Culpable Homicide not Amounting to Murder','Fire Incident','Dowry Death','Organised Crime',
  'Maharashtra Control of Organised Crime Act 1999',
  'Misappropriation of property & cruelty by inlaws','Forgery','Receiver of Stolen Property',
  'Explosive Substances Act 1908','Foreigners Act 1946','Juvenile Justice Act 2000',
  'Miscarriage Etc.','Prevention of Atrocities SC/ST Act 1989','House/Criminal Trespass',
  'Abduction','Protection of Women Domestic Violence Act 2005','Dacoity',
  'Concealment of birth','Riot','Offence against Public Servant','Stereo Theft',
  'wrongful Confinement/restraint','Public Nuisance','National Security Act 1980',
  'Impersonation','Assault on Public Servant','Passport Act 1967','Terrorist Act',
  'Prevention of Damage of Public Property Act 1984','M.V. Theft','Drugging/ Poisoning',
  'Escape from Police Custody','Civil Rights Act','Election Offences',
  'Drugs and Cosmetics Act 1940','Offences Relating to religion',
  'Essential Commodities Act 1955','Central Motor Vehicles Rules 1989',
  'Motor Vehicle Act,1988','Delhi Control of vehicular and Other Traffic on Road Act',
  'Prevention of Corruption Act 1988','Delhi Preservation of Trees Act, 1994',
  'Juvenile Justice Act 2010','Pre-conception and pre-natal diagnostic [pndt]',
  'Protection of human rights Act 1993','Cycle Theft',
  'Sedition or Offences against State','Poisons Act 1919',
  'Bombay Prevention of Begging Act 1959','Child Marriage Restraint Act 1929',
  'Official Secrets Act,1923','Un-Natural Death / Inquest Report','Cattle Theft',
  'M.V. Accessories Theft','Unlawful Activities (Prevention) Act 1967',
  'Personating public servant','Unnatural Offences(SODOMY)',
];
const CRIME_HEAD_OPTS = JSON.stringify(CRIME_HEADS.map(h => ({ value: h, label_en: h, label_hi: h })));

const ALL_TYPES = JSON.stringify(['CASE', 'ARREST', 'PCR_CALL', 'MISSING', 'UIDB']);

const fields = [
  // ─────────────────────────────────────────────────────────────────────────────
  // SHARED FIELDS (applicable to multiple record types — ONE row each)
  // ─────────────────────────────────────────────────────────────────────────────

  // io_name — IO / Enquiry Officer name, shared across ALL record types
  { id: 'C_17', field_key: 'io_name',           field_type: 'TEXT',   applicable_record_types: ALL_TYPES,                                             label_en: 'IO / Officer Name',           label_hi: 'जांच अधिकारी का नाम',          visible_to_levels: L, editable_by_levels: E, section: 'investigation_officer',   sort_order: 17, validation_rules: JSON.stringify({ required: false }) },

  // status — record status, shared across ALL types; TEXT so each type stores its own value
  { id: 'C_22', field_key: 'status',            field_type: 'TEXT',   applicable_record_types: ALL_TYPES,                                             label_en: 'Status',                      label_hi: 'स्थिति',                        visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 333, validation_rules: JSON.stringify({ required: false }) },

  // act_name — Act / Law name, shared by CASE and ARREST
  { id: 'C_10', field_key: 'act_name',          field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE', 'ARREST']),                    label_en: 'Act / Law Name',              label_hi: 'अधिनियम / कानून का नाम',        visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 10 },

  // sections — IPC sections, shared by CASE and ARREST
  { id: 'C_11', field_key: 'sections',          field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE', 'ARREST']),                    label_en: 'Sections',                    label_hi: 'धाराएं',                        visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 11 },

  // gd_no — GD number, shared by CASE and PCR_CALL
  { id: 'C_3',  field_key: 'gd_no',             field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE', 'PCR_CALL']),                  label_en: 'GD Number',                   label_hi: 'जीडी नंबर',                     visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 3,  validation_rules: JSON.stringify({ required: false }) },

  // gd_date — GD date, shared by CASE and PCR_CALL
  { id: 'C_4',  field_key: 'gd_date',           field_type: 'DATE',   applicable_record_types: JSON.stringify(['CASE', 'PCR_CALL']),                  label_en: 'GD Date',                     label_hi: 'जीडी दिनांक',                   visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 4 },

  // gd_time — GD time, shared by CASE and PCR_CALL
  { id: 'C_5',  field_key: 'gd_time',           field_type: 'TIME',   applicable_record_types: JSON.stringify(['CASE', 'PCR_CALL']),                  label_en: 'GD Time',                     label_hi: 'जीडी समय',                      visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 5 },

  // occurrence_place — Place of occurrence, shared by CASE and PCR_CALL
  { id: 'C_8',  field_key: 'occurrence_place',  field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE', 'PCR_CALL']),                  label_en: 'Place of Occurrence',         label_hi: 'घटना का स्थान',                 visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 8,  validation_rules: JSON.stringify({ required: false }) },

  // io_mobile — IO mobile number, shared by CASE, ARREST and UIDB
  { id: 'C_19', field_key: 'io_mobile',         field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE', 'ARREST', 'UIDB']),            label_en: 'IO Mobile No.',               label_hi: 'जांच अधिकारी का मोबाइल',        visible_to_levels: L, editable_by_levels: E, section: 'investigation_officer',   sort_order: 19 },

  // dd_no — DD number, shared by MISSING and UIDB
  { id: 'MS_1', field_key: 'dd_no',             field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'DD Number',                   label_hi: 'डीडी संख्या',                   visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 1 },

  // dd_date — DD date, shared by MISSING and UIDB
  { id: 'MS_2', field_key: 'dd_date',           field_type: 'DATE',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'DD Date',                     label_hi: 'डीडी दिनांक',                   visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 2 },

  // informant_name — Informant name, shared by MISSING and UIDB
  { id: 'MS_10',field_key: 'informant_name',    field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Informant Name',              label_hi: 'सूचना देने वाले का नाम',         visible_to_levels: L, editable_by_levels: E, section: 'contacts_assigned',       sort_order: 10 },

  // zipnet_no — ZIPNET number, shared by MISSING and UIDB
  { id: 'MS_13',field_key: 'zipnet_no',         field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'ZIPNET No.',                  label_hi: 'जिपनेट संख्या',                 visible_to_levels: L, editable_by_levels: E, section: 'contacts_assigned',       sort_order: 13 },

  // gender — shared by MISSING and UIDB (combined options: Male/Female/Other/Unknown)
  { id: 'MS_5', field_key: 'gender',            field_type: 'SELECT', applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Gender',                      label_hi: 'लिंग',                          visible_to_levels: L, editable_by_levels: E, section: 'person_details',          sort_order: 5,  validation_rules: JSON.stringify({ required: false }), options: JSON.stringify([{ value: 'Male', label_en: 'Male', label_hi: 'पुरुष' }, { value: 'Female', label_en: 'Female', label_hi: 'महिला' }, { value: 'Other', label_en: 'Other', label_hi: 'अन्य' }, { value: 'Unknown', label_en: 'Unknown', label_hi: 'अज्ञात' }]) },

  // Physical description fields — shared by MISSING and UIDB
  { id: 'MS_16',field_key: 'height',            field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Height',                      label_hi: 'कद',                            visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 16, is_active: true, scope_level: 'global' },
  { id: 'MS_17',field_key: 'built',             field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Built',                       label_hi: 'शरीर की बनावट',                 visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 17, is_active: true, scope_level: 'global' },
  { id: 'MS_18',field_key: 'complexion',        field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Complexion',                  label_hi: 'रंग',                           visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 18, is_active: true, scope_level: 'global' },
  { id: 'MS_20',field_key: 'face',              field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Face',                        label_hi: 'चेहरा',                         visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 20, is_active: true, scope_level: 'global' },
  { id: 'MS_21',field_key: 'hair',              field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Hair',                        label_hi: 'बाल',                           visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 21, is_active: true, scope_level: 'global' },
  { id: 'MS_22',field_key: 'moustache',         field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Moustache',                   label_hi: 'मूंछ',                          visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 22, is_active: true, scope_level: 'global' },
  { id: 'MS_26',field_key: 'beard',             field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Beard',                       label_hi: 'दाढ़ी',                         visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 23, is_active: true, scope_level: 'global' },
  { id: 'MS_27',field_key: 'upper_dress_color', field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Upper Dress Color',           label_hi: 'ऊपरी पोशाक का रंग',            visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 19, is_active: true, scope_level: 'global' },
  { id: 'MS_28',field_key: 'lower_dress_color', field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING', 'UIDB']),                   label_en: 'Lower Dress Color',           label_hi: 'निचली पोशाक का रंग',            visible_to_levels: L, editable_by_levels: E, section: 'physical_description',    sort_order: 20, is_active: true, scope_level: 'global' },

  // ─────────────────────────────────────────────────────────────────────────────
  // CASE (FIR) MODULE — fields unique to CASE
  // ─────────────────────────────────────────────────────────────────────────────
  { id: 'C_29', field_key: 'case_type',                   field_type: 'SELECT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Case Registration Type',                  label_hi: 'मामला पंजीकरण प्रकार',                  visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 0,  validation_rules: JSON.stringify({ required: false }), options: JSON.stringify([{ value: 'cctns(manual FIR)', label_en: 'cctns(manual FIR)', label_hi: 'सीसीटीएनएस (मैनुअल एफआईआर)' }, { value: 'eTheft', label_en: 'eTheft', label_hi: 'ई-चोरी' }, { value: 'eMVT', label_en: 'eMVT', label_hi: 'ई-एमवीटी' }, { value: 'NCRP', label_en: 'NCRP', label_hi: 'एनसीआरपी' }, { value: 'zero FIR', label_en: 'zero FIR', label_hi: 'जीरो एफआईआर' }]) },
  { id: 'C_1',  field_key: 'fir_no',                      field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'FIR Number',                              label_hi: 'प्राथमिकी (FIR) संख्या',                visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 1,  validation_rules: JSON.stringify({ required: false }) },
  { id: 'C_2',  field_key: 'fir_date',                    field_type: 'DATE',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'FIR Date',                                label_hi: 'एफआईआर तिथि',                           visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 2,  validation_rules: JSON.stringify({ required: false }) },
  { id: 'C_6',  field_key: 'beat_no',                     field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Beat No.',                                label_hi: 'बीट नंबर',                              visible_to_levels: L, editable_by_levels: E, section: 'general_info',            sort_order: 6 },
  { id: 'C_7',  field_key: 'occurrence_date',             field_type: 'DATE',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Date of Occurrence',                      label_hi: 'घटना की तिथि',                          visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 7,  validation_rules: JSON.stringify({ required: false }) },
  { id: 'C_9',  field_key: 'local_head',                  field_type: 'SELECT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Local Head (Crime)',                       label_hi: 'स्थानीय अपराध शीर्ष',                   visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 9,  validation_rules: JSON.stringify({ required: false }), is_active: true, scope_level: 'global', options: CRIME_HEAD_OPTS },
  { id: 'C_12', field_key: 'brief_facts',                 field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Brief Facts of the Case',                 label_hi: 'मामले का संक्षिप्त विवरण',              visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 12, validation_rules: JSON.stringify({ required: false }), full_width: true },
  { id: 'C_13', field_key: 'complainant_name',            field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Complainant Name',                         label_hi: 'शिकायतकर्ता का नाम',                    visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 13, validation_rules: JSON.stringify({ required: false }) },
  { id: 'C_14', field_key: 'complainant_address',         field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Complainant Address',                      label_hi: 'शिकायतकर्ता का पता',                    visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 14 },
  { id: 'C_18', field_key: 'io_pis',                      field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'PIS No. of IO',                           label_hi: 'जांच अधिकारी का पीआईएस नंबर',           visible_to_levels: L, editable_by_levels: E, section: 'investigation_officer',   sort_order: 18 },
  { id: 'C_20', field_key: 'property_description',        field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Property Description',                    label_hi: 'संपत्ति का विवरण',                      visible_to_levels: L, editable_by_levels: E, section: 'recovered_property',      sort_order: 341, full_width: true },
  { id: 'C_21', field_key: 'property_status',             field_type: 'SELECT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Property Status',                         label_hi: 'संपत्ति की स्थिति',                     visible_to_levels: L, editable_by_levels: E, section: 'stolen_property',         sort_order: 332, options: JSON.stringify([{ value: 'Stolen', label_en: 'Stolen', label_hi: 'चोरी हुई' }, { value: 'NA', label_en: 'N/A', label_hi: 'लागू नहीं' }]) },
  { id: 'C_23', field_key: 'remarks',                     field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Remarks',                                 label_hi: 'टिप्पणियां',                            visible_to_levels: L, editable_by_levels: E, section: 'stolen_property',         sort_order: 334, full_width: true },
  { id: 'C_26', field_key: 'time_of_occurrence',          field_type: 'TIME',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Time of Occurrence',                      label_hi: 'घटना का समय',                           visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 26, is_active: true, scope_level: 'global' },
  { id: 'C_30', field_key: 'complainant_parent_name',     field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Complainant Parent Name',                 label_hi: 'शिकायतकर्ता के माता/पिता का नाम',       visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 14, is_active: true, scope_level: 'global' },
  { id: 'C_35', field_key: 'complainant_age',             field_type: 'NUMBER',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Complainant Age',                         label_hi: 'शिकायतकर्ता की आयु',                    visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 15, is_active: true, scope_level: 'global' },
  { id: 'C_33', field_key: 'stolen_property',             field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Property Description',                    label_hi: 'संपत्ति का विवरण',                      visible_to_levels: L, editable_by_levels: E, section: 'stolen_property',         sort_order: 331, is_active: true, scope_level: 'global', full_width: true },
  { id: 'C_34', field_key: 'recovered_property',          field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Recovery Property',                       label_hi: 'बरामद की गई संपत्ति',                   visible_to_levels: L, editable_by_levels: E, section: 'recovered_property',      sort_order: 342, is_active: true, scope_level: 'global', full_width: true },
  { id: 'C_36', field_key: 'recovered_property_status',   field_type: 'SELECT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Property Status',                         label_hi: 'संपत्ति की स्थिति',                     visible_to_levels: L, editable_by_levels: E, section: 'recovered_property',      sort_order: 343, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Recovered', label_en: 'Recovered', label_hi: 'बरामद' }, { value: 'NA', label_en: 'N/A', label_hi: 'लागू नहीं' }]) },
  { id: 'C_37', field_key: 'recovered_case_status',       field_type: 'SELECT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Case Status',                             label_hi: 'मामले की स्थिति',                       visible_to_levels: L, editable_by_levels: E, section: 'recovered_property',      sort_order: 344, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Open', label_en: 'Open', label_hi: 'लंबित' }, { value: 'Chargesheeted', label_en: 'Chargesheeted', label_hi: 'चार्जशीट' }, { value: 'Closed', label_en: 'Closed', label_hi: 'बंद' }]) },
  { id: 'C_38', field_key: 'recovered_remarks',           field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Remarks',                                 label_hi: 'टिप्पणियां',                            visible_to_levels: L, editable_by_levels: E, section: 'recovered_property',      sort_order: 345, is_active: true, scope_level: 'global', full_width: true },

  // Phone theft fields (conditional on crime head)
  { id: 'PH_1', field_key: 'phone_make',                  field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Phone Make / Brand',                      label_hi: 'फोन का ब्रांड',                         visible_to_levels: L, editable_by_levels: E, section: 'Property Details',        sort_order: 310, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['Mobile Theft', 'Snatching', 'Robbery'] }) },
  { id: 'PH_2', field_key: 'phone_model',                 field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Phone Model',                             label_hi: 'फोन का मॉडल',                           visible_to_levels: L, editable_by_levels: E, section: 'Property Details',        sort_order: 311, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['Mobile Theft', 'Snatching', 'Robbery'] }) },
  { id: 'PH_3', field_key: 'phone_imei',                  field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'IMEI Number',                             label_hi: 'आईएमईआई नंबर',                          visible_to_levels: L, editable_by_levels: E, section: 'Property Details',        sort_order: 312, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['Mobile Theft', 'Snatching', 'Robbery'] }) },
  { id: 'PH_4', field_key: 'phone_color',                 field_type: 'TEXT',     applicable_record_types: JSON.stringify(['CASE']), label_en: 'Phone Color',                             label_hi: 'फोन का रंग',                            visible_to_levels: L, editable_by_levels: E, section: 'Property Details',        sort_order: 313, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['Mobile Theft', 'Snatching', 'Robbery'] }) },
  { id: 'PH_5', field_key: 'phone_status',                field_type: 'SELECT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Phone Recovery Status',                   label_hi: 'फोन बरामदगी स्थिति',                    visible_to_levels: L, editable_by_levels: E, section: 'Property Details',        sort_order: 314, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['Mobile Theft', 'Snatching', 'Robbery'] }), options: JSON.stringify([{ value: 'NOT_RECOVERED', label_en: 'Not Recovered', label_hi: 'बरामद नहीं' }, { value: 'RECOVERED', label_en: 'Recovered', label_hi: 'बरामद' }, { value: 'PARTIAL', label_en: 'Partially Recovered', label_hi: 'आंशिक रूप से बरामद' }]) },

  // Daily Diary extra CASE fields
  { id: 'DD_C1',  field_key: 'complainant_father_husband_name', field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE']), label_en: "Complainant's Father / Husband Name",   label_hi: 'शिकायतकर्ता के पिता / पति का नाम',     visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 14, is_active: true, scope_level: 'global' },
  { id: 'DD_C2',  field_key: 'accused_name',                    field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Accused Name',                          label_hi: 'अभियुक्त का नाम',                       visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 20, is_active: true, scope_level: 'global' },
  { id: 'DD_C3',  field_key: 'accused_father_name',             field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE']), label_en: "Accused Father's Name",                 label_hi: 'अभियुक्त के पिता का नाम',               visible_to_levels: L, editable_by_levels: E, section: 'complainant_accused_info', sort_order: 21, is_active: true, scope_level: 'global' },
  { id: 'DD_C4',  field_key: 'occurrence_time',                 field_type: 'TIME',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Time of Occurrence',                    label_hi: 'घटना का समय',                           visible_to_levels: L, editable_by_levels: E, section: 'incident_details',        sort_order: 8,  is_active: true, scope_level: 'global' },
  { id: 'DD_C5',  field_key: 'vehicle_no',                      field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'Vehicle Registration No.',               label_hi: 'वाहन पंजीकरण संख्या',                   visible_to_levels: L, editable_by_levels: E, section: 'vehicle_details',         sort_order: 50, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['M.V. Theft', 'M.V. Accessories Theft', 'Cycle Theft', 'Robbery', 'Snatching'] }) },
  { id: 'DD_C6',  field_key: 'vehicle_type',                    field_type: 'SELECT', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Vehicle Type',                          label_hi: 'वाहन का प्रकार',                        visible_to_levels: L, editable_by_levels: E, section: 'vehicle_details',         sort_order: 51, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['M.V. Theft', 'M.V. Accessories Theft', 'Cycle Theft', 'Robbery', 'Snatching'] }), options: JSON.stringify([{ value: 'Car', label_en: 'Car', label_hi: 'कार' }, { value: 'Motorcycle', label_en: 'Motorcycle', label_hi: 'मोटरसाइकिल' }, { value: 'Scooter', label_en: 'Scooter', label_hi: 'स्कूटर' }, { value: 'E-Rickshaw', label_en: 'E-Rickshaw', label_hi: 'ई-रिक्शा' }, { value: 'Auto', label_en: 'Auto Rickshaw', label_hi: 'ऑटो रिक्शा' }, { value: 'Tempo', label_en: 'Tempo / Truck', label_hi: 'टेम्पो / ट्रक' }, { value: 'Cycle', label_en: 'Bicycle', label_hi: 'साइकिल' }, { value: 'Other', label_en: 'Other', label_hi: 'अन्य' }]) },
  { id: 'DD_C7',  field_key: 'cd_uploaded_24h',                 field_type: 'SELECT', applicable_record_types: JSON.stringify(['CASE']), label_en: '1st CD Uploaded Within 24 Hours',       label_hi: 'पहली सीडी 24 घंटे में अपलोड की गई',    visible_to_levels: L, editable_by_levels: E, section: 'vehicle_details',         sort_order: 52, is_active: true, scope_level: 'global', show_when: JSON.stringify({ field: 'local_head', value: ['M.V. Theft', 'M.V. Accessories Theft'] }), options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_C8',  field_key: 'footage_collected',               field_type: 'SELECT', applicable_record_types: JSON.stringify(['CASE']), label_en: 'CCTV Footage Collected',                label_hi: 'सीसीटीवी फुटेज एकत्र किया गया',        visible_to_levels: L, editable_by_levels: E, section: 'vehicle_details',         sort_order: 53, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_C9',  field_key: 'rc_no',                           field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE']), label_en: 'RC No.',                                label_hi: 'आरसी संख्या',                           visible_to_levels: L, editable_by_levels: E, section: 'investigation_details',   sort_order: 60, is_active: true, scope_level: 'global' },
  { id: 'DD_C10', field_key: 'disposal_type',                   field_type: 'SELECT', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Disposal Type',                         label_hi: 'निपटान प्रकार',                         visible_to_levels: L, editable_by_levels: E, section: 'investigation_details',   sort_order: 61, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Challan', label_en: 'Challan', label_hi: 'चालान' }, { value: 'Untrace', label_en: 'Untraced', label_hi: 'अपता' }, { value: 'Cancel', label_en: 'Cancelled', label_hi: 'रद्द' }]) },
  { id: 'DD_C11', field_key: 'cause_of_death',                  field_type: 'SELECT', applicable_record_types: JSON.stringify(['CASE']), label_en: 'Cause of Death',                        label_hi: 'मृत्यु का कारण',                        visible_to_levels: L, editable_by_levels: E, section: 'inquest_details',         sort_order: 70, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Accidental', label_en: 'Accidental', label_hi: 'दुर्घटना' }, { value: 'Natural', label_en: 'Natural', label_hi: 'प्राकृतिक' }, { value: 'Suicide', label_en: 'Suicide', label_hi: 'आत्महत्या' }, { value: 'Murder', label_en: 'Murder', label_hi: 'हत्या' }, { value: 'Unknown', label_en: 'Unknown', label_hi: 'अज्ञात' }]) },
  { id: 'DD_C12', field_key: 'deceased_father_husband_name',    field_type: 'TEXT',   applicable_record_types: JSON.stringify(['CASE']), label_en: "Deceased's Father / Husband Name",      label_hi: 'मृतक के पिता / पति का नाम',             visible_to_levels: L, editable_by_levels: E, section: 'inquest_details',         sort_order: 71, is_active: true, scope_level: 'global' },
  { id: 'DD_C13', field_key: 'is_important',                    field_type: 'BOOLEAN',applicable_record_types: JSON.stringify(['CASE']), label_en: 'Mark as Important Case',                label_hi: 'महत्वपूर्ण मामले के रूप में चिह्नित करें', visible_to_levels: L, editable_by_levels: E, section: 'general_info',         sort_order: 99, is_active: true, scope_level: 'global' },

  // ─────────────────────────────────────────────────────────────────────────────
  // ARREST MODULE — fields unique to ARREST
  // ─────────────────────────────────────────────────────────────────────────────
  { id: 'A_1',  field_key: 'linked_fir_dd_no',            field_type: 'NUMBER',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Linked FIR / DD No.',              label_hi: 'संबंधित एफआईआर / डीडी संख्या',         visible_to_levels: L, editable_by_levels: E, section: 'general_info',   sort_order: 1 },
  { id: 'A_4',  field_key: 'arrested_name',               field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Name of Arrested Person',          label_hi: 'गिरफ्तार व्यक्ति का नाम',              visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 4, validation_rules: JSON.stringify({ required: false }) },
  { id: 'A_5',  field_key: 'arrested_address',            field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Address of Arrested',              label_hi: 'गिरफ्तार का पता',                       visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 5 },
  { id: 'A_6',  field_key: 'arrest_date',                 field_type: 'DATE',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Date of Arrest',                   label_hi: 'गिरफ्तारी की तिथि',                    visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 6, validation_rules: JSON.stringify({ required: false }) },
  { id: 'A_7',  field_key: 'arrest_place',                field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Place of Arrest',                  label_hi: 'गिरफ्तारी का स्थान',                   visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 7 },
  { id: 'A_8',  field_key: 'crime_head',                  field_type: 'SELECT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Crime Head',                       label_hi: 'अपराध शीर्ष',                          visible_to_levels: L, editable_by_levels: E, section: 'offence_info',   sort_order: 8, validation_rules: JSON.stringify({ required: false }), is_active: true, scope_level: 'global', options: CRIME_HEAD_OPTS },
  { id: 'A_10', field_key: 'other_status_reason',         field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Other Status Reason',              label_hi: 'अन्य स्थिति का कारण',                  visible_to_levels: L, editable_by_levels: E, section: 'custody_status', sort_order: 10, show_when: JSON.stringify({ field: 'status', value: 'others' }) },
  { id: 'A_12', field_key: 'nafis_prepared',              field_type: 'BOOLEAN',  applicable_record_types: JSON.stringify(['ARREST']), label_en: 'NAFIS Prepared',                   label_hi: 'नाफिस तैयार किया गया',                 visible_to_levels: L, editable_by_levels: E, section: 'procedure_slips', sort_order: 12 },
  { id: 'A_13', field_key: 'dossier_prepared',            field_type: 'BOOLEAN',  applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Dossier Prepared',                 label_hi: 'डोजियर तैयार किया गया',                visible_to_levels: L, editable_by_levels: E, section: 'procedure_slips', sort_order: 13 },
  { id: 'A_14', field_key: 'age_gender',                  field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Age / Gender',                     label_hi: 'आयु / लिंग',                           visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 14, is_active: true, scope_level: 'global' },
  { id: 'A_15', field_key: 'nick_name',                   field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Nick Name',                        label_hi: 'उपनाम',                                visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 15, is_active: true, scope_level: 'global' },
  { id: 'A_16', field_key: 'parents_name',                field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Parents Name',                     label_hi: 'माता-पिता का नाम',                     visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 16, is_active: true, scope_level: 'global' },
  { id: 'A_17', field_key: 'prev_involvement',            field_type: 'SELECT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Prev. Involvement (Y/N)',           label_hi: 'पूर्व संलिप्तता (हाँ/नहीं)',           visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 17, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'A_18', field_key: 'recovery',                    field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Recovery',                         label_hi: 'बरामदगी',                              visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 18, is_active: true, scope_level: 'global', full_width: true },
  { id: 'A_19', field_key: 'bc_or_not',                   field_type: 'SELECT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'BC or Not',                        label_hi: 'बीसी है या नहीं',                      visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 19, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'A_22', field_key: 'nafis_dossier',               field_type: 'SELECT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'NAFIS / Dossier (Y/N)',            label_hi: 'नाफिस / डोजियर (हाँ/नहीं)',           visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 22, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'A_23', field_key: 'scheme',                      field_type: 'SELECT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Scheme (Special Scheme Arrest)',    label_hi: 'योजना (विशेष योजना गिरफ्तारी)',        visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 23, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Integrated PI', label_en: 'Integrated PI', label_hi: 'एकीकृत पीआई' }, { value: 'Grp patrolling', label_en: 'Group Patrolling', label_hi: 'समूह गश्त' }, { value: 'Cycle patrol', label_en: 'Cycle Patrol', label_hi: 'साइकिल गश्त' }, { value: 'Anti-snatching', label_en: 'Anti-Snatching Team', label_hi: 'छीना-झपटी रोधी दल' }, { value: 'PRAHARI', label_en: 'PRAHARI', label_hi: 'प्रहरी' }, { value: 'Eye & ear', label_en: 'Eyes & Ears Scheme Members', label_hi: 'नेत्र और कान योजना सदस्य' }]) },
  { id: 'A_25', field_key: 'io_rank',                     field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'IO Rank',                          label_hi: 'जांच अधिकारी का पद',                   visible_to_levels: L, editable_by_levels: E, section: 'procedure_slips', sort_order: 25, is_active: true, scope_level: 'global' },
  { id: 'A_26', field_key: 'arrested_age',                field_type: 'NUMBER',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Age',                              label_hi: 'आयु',                                  visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 6,  is_active: true, scope_level: 'global' },
  { id: 'A_27', field_key: 'arresting_officer_mobile',    field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Contact of Arresting Officer',     label_hi: 'गिरफ्तार करने वाले अधिकारी का मोबाइल', visible_to_levels: L, editable_by_levels: E, section: 'procedure_slips', sort_order: 25, is_active: true, scope_level: 'global' },
  { id: 'A_28', field_key: 'io_mobile_2',                 field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Contact of IO',                    label_hi: 'जांच अधिकारी का मोबाइल',               visible_to_levels: L, editable_by_levels: E, section: 'procedure_slips', sort_order: 26, is_active: true, scope_level: 'global' },
  { id: 'A_29', field_key: 'is_po',                       field_type: 'SELECT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Is the person PO',                 label_hi: 'क्या व्यक्ति घोषित अपराधी (PO) है',   visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 24, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'A_30', field_key: 'arresting_officer',           field_type: 'TEXT',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arresting Officer',                label_hi: 'गिरफ्तार करने वाले अधिकारी',           visible_to_levels: L, editable_by_levels: E, section: 'procedure_slips', sort_order: 30, is_active: true, scope_level: 'global' },
  { id: 'A_31', field_key: 'arrest_time',                 field_type: 'TIME',     applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Time of Arrest',                   label_hi: 'गिरफ्तारी का समय',                     visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 7,  is_active: true, scope_level: 'global' },

  // Daily Diary extra ARREST fields
  { id: 'DD_A1',  field_key: 'arrested_father_husband_name', field_type: 'TEXT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: "Arrested Person's Father / Husband Name", label_hi: 'गिरफ्तार व्यक्ति के पिता / पति का नाम', visible_to_levels: L, editable_by_levels: E, section: 'arrestee_info',  sort_order: 5,  is_active: true, scope_level: 'global' },
  { id: 'DD_A2',  field_key: 'bad_character',               field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Is Bad Character (BC)',                   label_hi: 'बदमाश (बीसी) है या नहीं',               visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 20, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A3',  field_key: 'proclaimed_offender',         field_type: 'BOOLEAN',applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Proclaimed Offender (PO)',                label_hi: 'घोषित अपराधी (पीओ)',                    visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 21, is_active: true, scope_level: 'global' },
  { id: 'DD_A4',  field_key: 'listed_criminal',             field_type: 'BOOLEAN',applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Listed Criminal (BC)',                    label_hi: 'सूचीबद्ध अपराधी (बीसी)',                visible_to_levels: L, editable_by_levels: E, section: 'arrest_details', sort_order: 22, is_active: true, scope_level: 'global' },
  { id: 'DD_A5',  field_key: 'integrated_pi',               field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arrested via Integrated PI',              label_hi: 'एकीकृत पीआई से गिरफ्तार',              visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 30, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A6',  field_key: 'group_patrolling',            field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arrested via Group Patrolling',           label_hi: 'समूह गश्त से गिरफ्तार',                visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 31, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A7',  field_key: 'cycle_patrolling',            field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arrested via Cycle Patrolling',           label_hi: 'साइकिल गश्त से गिरफ्तार',              visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 32, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A8',  field_key: 'by_antisnatching_team',       field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arrested via Anti-Snatching Team',        label_hi: 'छीना-झपटी रोधी दल से गिरफ्तार',       visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 33, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A9',  field_key: 'by_prahari',                  field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arrested via PRAHARI Scheme',             label_hi: 'प्रहरी योजना से गिरफ्तार',             visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 34, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A10', field_key: 'by_eyes_ears_scheme_members', field_type: 'SELECT', applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Arrested via Eyes & Ears Scheme',         label_hi: 'नेत्र और कान योजना से गिरफ्तार',      visible_to_levels: L, editable_by_levels: E, section: 'special_scheme', sort_order: 35, is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Yes', label_en: 'Yes', label_hi: 'हाँ' }, { value: 'No', label_en: 'No', label_hi: 'नहीं' }]) },
  { id: 'DD_A11', field_key: 'cheated_amount',              field_type: 'TEXT',   applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Amount Cheated / Defrauded',              label_hi: 'धोखाधड़ी की गई राशि',                  visible_to_levels: L, editable_by_levels: E, section: 'financial_fraud', sort_order: 40, is_active: true, scope_level: 'global' },
  { id: 'DD_A12', field_key: 'modus_operandi',              field_type: 'TEXTAREA',applicable_record_types: JSON.stringify(['ARREST']), label_en: 'Modus Operandi',                         label_hi: 'अपराध करने का तरीका',                  visible_to_levels: L, editable_by_levels: E, section: 'financial_fraud', sort_order: 41, is_active: true, scope_level: 'global', full_width: true },

  // ─────────────────────────────────────────────────────────────────────────────
  // PCR / KALANDRA MODULE — fields unique to PCR_CALL
  // ─────────────────────────────────────────────────────────────────────────────
  { id: 'P_1',  field_key: 'pcr_no',                       field_type: 'TEXT',     applicable_record_types: JSON.stringify(['PCR_CALL']), label_en: 'PCR Number',             label_hi: 'पीसीआर नंबर',                  visible_to_levels: L, editable_by_levels: E, section: 'informant_contact', sort_order: 1 },
  { id: 'P_5',  field_key: 'call_head',                    field_type: 'SELECT',   applicable_record_types: JSON.stringify(['PCR_CALL']), label_en: 'Call Category (Head)',    label_hi: 'कॉल श्रेणी',                   visible_to_levels: L, editable_by_levels: E, section: 'complaint_details', sort_order: 5, validation_rules: JSON.stringify({ required: false }), is_active: true, scope_level: 'global', options: CRIME_HEAD_OPTS },
  { id: 'P_6',  field_key: 'call_gist',                    field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['PCR_CALL']), label_en: 'PCR Call Gist',          label_hi: 'पीसीआर कॉल का विवरण',          visible_to_levels: L, editable_by_levels: E, section: 'complaint_details', sort_order: 6, validation_rules: JSON.stringify({ required: false }), full_width: true },
  { id: 'P_7',  field_key: 'caller_name',                  field_type: 'TEXT',     applicable_record_types: JSON.stringify(['PCR_CALL']), label_en: 'Caller Name',            label_hi: 'कॉलर का नाम',                  visible_to_levels: L, editable_by_levels: E, section: 'informant_contact', sort_order: 7 },
  { id: 'P_8',  field_key: 'caller_mobile',                field_type: 'NUMBER',   applicable_record_types: JSON.stringify(['PCR_CALL']), label_en: 'Caller Mobile',          label_hi: 'कॉलर का मोबाइल',               visible_to_levels: L, editable_by_levels: E, section: 'informant_contact', sort_order: 8 },
  { id: 'P_10', field_key: 'arrival_time',                 field_type: 'TIME',     applicable_record_types: JSON.stringify(['PCR_CALL']), label_en: 'Arrival Time',           label_hi: 'पहुंचने का समय',                visible_to_levels: L, editable_by_levels: E, section: 'arrival_geo',       sort_order: 10 },

  // ─────────────────────────────────────────────────────────────────────────────
  // MISSING PERSON MODULE — fields unique to MISSING (shared fields defined above)
  // ─────────────────────────────────────────────────────────────────────────────
  { id: 'MS_3', field_key: 'missing_name',                 field_type: 'TEXT',     applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Name of Missing Person', label_hi: 'लापता व्यक्ति का नाम',          visible_to_levels: L, editable_by_levels: E, section: 'person_details',       sort_order: 3, validation_rules: JSON.stringify({ required: false }) },
  { id: 'MS_4', field_key: 'age',                          field_type: 'NUMBER',   applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Age',                    label_hi: 'उम्र',                          visible_to_levels: L, editable_by_levels: E, section: 'person_details',       sort_order: 4 },
  { id: 'MS_6', field_key: 'major_minor',                  field_type: 'RADIO',    applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Major / Minor',          label_hi: 'वयस्क / नाबालिग',              visible_to_levels: L, editable_by_levels: E, section: 'person_details',       sort_order: 6, options: JSON.stringify([{ value: 'Major', label_en: 'Major (18+)', label_hi: 'वयस्क (18+)' }, { value: 'Minor', label_en: 'Minor (Below 18)', label_hi: 'नाबालिग (18 से कम)' }]) },
  { id: 'MS_7', field_key: 'missing_date',                 field_type: 'DATE',     applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Date Missing Since',     label_hi: 'लापता होने की तिथि',            visible_to_levels: L, editable_by_levels: E, section: 'location_particulars', sort_order: 7, validation_rules: JSON.stringify({ required: false }) },
  { id: 'MS_8', field_key: 'missing_place',                field_type: 'TEXT',     applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Last Seen Place',        label_hi: 'अंतिम बार देखा गया स्थान',     visible_to_levels: L, editable_by_levels: E, section: 'location_particulars', sort_order: 8 },
  { id: 'MS_9', field_key: 'physical_description',         field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Physical Description',   label_hi: 'शारीरिक हुलिया',                visible_to_levels: L, editable_by_levels: E, section: 'physical_description', sort_order: 0, full_width: true },
  { id: 'MS_11',field_key: 'informant_mobile',             field_type: 'NUMBER',   applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Informant Mobile',       label_hi: 'सूचना देने वाले का मोबाइल',    visible_to_levels: L, editable_by_levels: E, section: 'contacts_assigned',    sort_order: 11 },
  { id: 'MS_15',field_key: 'mp_address',                   field_type: 'TEXT',     applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Address of Missing Person', label_hi: 'लापता व्यक्ति का पता',       visible_to_levels: L, editable_by_levels: E, section: 'person_details',       sort_order: 15, is_active: true, scope_level: 'global' },
  { id: 'MS_19',field_key: 'dress_color',                  field_type: 'TEXT',     applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Dress & Color',          label_hi: 'पहनावा और रंग',                 visible_to_levels: L, editable_by_levels: E, section: 'physical_description', sort_order: 19, is_active: true, scope_level: 'global' },
  { id: 'MS_23',field_key: 'missing_type',                 field_type: 'SELECT',   applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Missing / Found Type',   label_hi: 'लापता / मिला प्रकार',          visible_to_levels: L, editable_by_levels: E, section: 'general_info',         sort_order: 3,  is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'Missing', label_en: 'Missing', label_hi: 'लापता' }, { value: 'Found', label_en: 'Found', label_hi: 'मिला' }]) },
  { id: 'MS_24',field_key: 'pcr_call_flag',                field_type: 'BOOLEAN',  applicable_record_types: JSON.stringify(['MISSING']), label_en: 'PCR Call (Y/N)',         label_hi: 'पीसीआर कॉल (हाँ/नहीं)',         visible_to_levels: L, editable_by_levels: E, section: 'general_info',         sort_order: 4,  is_active: true, scope_level: 'global' },
  { id: 'MS_25',field_key: 'operator_name',                field_type: 'TEXT',     applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Operator Name to Whom MPS', label_hi: 'ऑपरेटर का नाम जिसे एमपीएस भेजा गया', visible_to_levels: L, editable_by_levels: E, section: 'general_info',    sort_order: 5,  is_active: true, scope_level: 'global' },

  // Daily Diary extra MISSING fields
  { id: 'DD_M1',  field_key: 'missing_address',            field_type: 'TEXT',   applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Address of Missing Person (Alt.)', label_hi: 'लापता व्यक्ति का पता (वैकल्पिक)', visible_to_levels: L, editable_by_levels: E, section: 'person_details', sort_order: 16, is_active: true, scope_level: 'global' },
  { id: 'DD_M2',  field_key: 'source',                     field_type: 'SELECT', applicable_record_types: JSON.stringify(['MISSING']), label_en: 'Source of Information',            label_hi: 'सूचना का स्रोत',                  visible_to_levels: L, editable_by_levels: E, section: 'general_info',   sort_order: 2,  is_active: true, scope_level: 'global', options: JSON.stringify([{ value: 'PCR', label_en: 'PCR Call', label_hi: 'पीसीआर कॉल' }, { value: 'DD', label_en: 'DD / Written Complaint', label_hi: 'डीडी / लिखित शिकायत' }]) },

  // ─────────────────────────────────────────────────────────────────────────────
  // UIDB (Unidentified Bodies) MODULE — fields unique to UIDB
  // ─────────────────────────────────────────────────────────────────────────────
  { id: 'U_2',  field_key: 'found_date',                   field_type: 'DATE',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Date Body Found',                label_hi: 'शव मिलने की तिथि',              visible_to_levels: L, editable_by_levels: E, section: 'discovery_details', sort_order: 2, validation_rules: JSON.stringify({ required: false }) },
  { id: 'U_3',  field_key: 'found_place',                  field_type: 'TEXT',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Place Body Found',               label_hi: 'शव मिलने का स्थान',             visible_to_levels: L, editable_by_levels: E, section: 'discovery_details', sort_order: 3, validation_rules: JSON.stringify({ required: false }) },
  { id: 'U_5',  field_key: 'approx_age',                   field_type: 'TEXT',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Approximate Age',                label_hi: 'अनुमानित उम्र',                 visible_to_levels: L, editable_by_levels: E, section: 'corpse_desc',       sort_order: 5 },
  { id: 'U_6',  field_key: 'description',                  field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Physical Description',           label_hi: 'शारीरिक हुलिया',                visible_to_levels: L, editable_by_levels: E, section: 'corpse_desc',       sort_order: 6, full_width: true },
  { id: 'U_10', field_key: 'identified',                   field_type: 'BOOLEAN',  applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Body Identified',                label_hi: 'शव की पहचान हुई',               visible_to_levels: L, editable_by_levels: E, section: 'zipnet_status',     sort_order: 10 },
  { id: 'U_12', field_key: 'cause',                        field_type: 'TEXT',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Cause',                          label_hi: 'कारण',                          visible_to_levels: L, editable_by_levels: E, section: 'uidb_details',      sort_order: 12, is_active: true, scope_level: 'global' },
  { id: 'U_13', field_key: 'uidb_physical_desc',           field_type: 'TEXTAREA', applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Physical Description',           label_hi: 'शारीरिक हुलिया',                visible_to_levels: L, editable_by_levels: E, section: 'uidb_details',      sort_order: 13, is_active: true, scope_level: 'global', full_width: true },
  { id: 'U_15', field_key: 'inquest_sections',             field_type: 'TEXT',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Under Section (If inquest)',     label_hi: 'धारा के तहत (यदि जांच हो)',    visible_to_levels: L, editable_by_levels: E, section: 'general_info',      sort_order: 3,  is_active: true, scope_level: 'global' },
  { id: 'U_16', field_key: 'deceased_name',                field_type: 'TEXT',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Name of Deceased',               label_hi: 'मृतक का नाम',                   visible_to_levels: L, editable_by_levels: E, section: 'corpse_desc',       sort_order: 1,  is_active: true, scope_level: 'global' },
  { id: 'U_17', field_key: 'deceased_address',             field_type: 'TEXT',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Address of Deceased',            label_hi: 'मृतक का पता',                   visible_to_levels: L, editable_by_levels: E, section: 'corpse_desc',       sort_order: 2,  is_active: true, scope_level: 'global' },
  { id: 'U_28', field_key: 'filed_by_acp_sdm_date',        field_type: 'DATE',     applicable_record_types: JSON.stringify(['UIDB']), label_en: 'Date of Filed by ACP/SDM',       label_hi: 'एसीपी/एसडीएम द्वारा दायर करने की तिथि', visible_to_levels: L, editable_by_levels: E, section: 'uidb_details', sort_order: 13, is_active: true, scope_level: 'global' },
];

const DEFAULTS = {
  is_active: true,
  scope_level: 'global',
  scope_id: null,
  created_by: null,
  section_label_en: null,
  section_label_hi: null,
};

export async function seed(knex) {
  const rows = fields.map(f => ({ ...DEFAULTS, ...f }));
  await knex('field_registry')
    .insert(rows)
    .onConflict('field_key')
    .merge([
      'label_en', 'label_hi', 'field_type', 'options', 'sort_order',
      'section', 'validation_rules', 'show_when', 'is_active',
      'applicable_record_types', 'visible_to_levels', 'editable_by_levels', 'full_width',
    ]);
  console.log(`[01_fields] Upserted ${rows.length} fields into field_registry`);
}
